### ISSUE TITLE
Viewport and UI

### ISSUE THREAD

**Issue by ShaunKulesa** [jonwright/pyopengltk#16]
With the library can I have a Tkinter UI and opengl viewport?

**Comment by jonwright** [comment]
Yes, but only on windows and linux for now. Still needs porting to mac...

**Comment by ShaunKulesa** [comment]
Ok cool, well done with this library. I've been looking to make a small 2d game engine project and this looks good.

**Comment by ShaunKulesa** [comment]
Also is there any docs or tutorials for this? i tried adding a button to the example with the green screen but it did not show anywhere.
