### ISSUE TITLE
Viewport messing up UI.

### ISSUE THREAD

**Issue by ShaunKulesa** [jonwright/pyopengltk#17]
Sorry to bother you again but the `open_gl_frame` = AppOgl(self, width=1000, height=500)` is messing up my UI. When i have my buttons without the Opengl they are in a row next to each other but with opengl they are placed weirdly.
[test.txt](https://github.com/jonwright/pyopengltk/files/5466185/test.txt)

**Comment by jonwright** [comment]
Sorry, I don't have time to take a look right now, but did you try putting a label with a static image into the same place in your grid? Usually I use pack:
https://github.com/jonwright/ImageD11/blob/master/ImageD11src/tkGui/plot3d.py
https://github.com/jonwright/fabian/blob/master/Fabian/ReliefPlot.py

**Comment by ShaunKulesa** [comment]
I tried doing that, but it didnt work. I'll be working on pyopengl for now so if you get anytime to look at it many thanks.

**Comment by jonwright** [comment]
Did you mean to add "columnspan=3" after "row=1" in your call to grid? It doesn't look like a bug to me, just a grid where the frame  is a large item in the first column:
```
Button             |  Button    |  Button
Frame              |   empty    |  empty
```
