### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by Aareon** [jonwright/pyopengltk#2]
Are you satisfied leaving this project with no license, or do you have a license preference? Below are the implications of choosing no license.
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

Source: https://help.github.com/en/articles/licensing-a-repository

**Comment by einarf** [comment]
This one is definitely important to resolve.

**Comment by jonwright** [comment]
For simplicity I would prefer MIT and I am happy to add that one if it resolves the question?
But: there is code which was copied from pyopengl for compatibility and they have a custom license, so perhaps theirs should be added too.

**Comment by einarf** [comment]
I think MIT would work. Whatever you think is the right thing to do.
