### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by ShaunKulesa** [jonwright/pyopengltk#21]
@jonwright do you have an email I can contact you by so I don't spamn your issues. I need to ask about converting c to python. It's about a header.

**Comment by einarf** [comment]
Probably better places to ask for help around this? There are online python communities. For example the python discord (https://youtu.be/ZH26PuX3re0)

For most project the github issues are pretty much limited to bugs and very specific quetions about the library itself.

**Comment by ShaunKulesa** [comment]
I doubt many developers on the python discord know bout converting C to python. I know john has so thats why i want to contact them privately so i dont have to type in the "issues" section.

**Comment by jonwright** [comment]
There is an email for me in setup.py  - did you try it already ? I sometimes ask on stackoverflow and/or reddit if I can't find an answer with google. I would guess the nim forums have a lot of experts who speak both C and python better than me.
