### ISSUE TITLE
Animation not stopping when variable = False. it prints false but the animation does not stop.

### ISSUE THREAD

**Issue by ShaunKulesa** [jonwright/pyopengltk#23]
`while self.runv == True:`
    `   self.app.animate = 1`
    `   self.app.after(100, self.app.printContext)`
    `   self.app.mainloop()`
`else:`
    `   print("false")`
    `   self.app.animate = 0`
    `   self.app.after(100, self.app.printContext)`
    `   self.app.mainloop()`

**Comment by ShaunKulesa** [comment]
updated code but animation still carrying on. and yes the loop does work. it prints true and false when needed.

```
while self.runv == True:
      print("true")
      self.app.animate = 1
     self.app.after(100, self.app.printContext)
     self.app.mainloop()

print("false")
self.runv = False
self.app.animate = 0
self.app.after(100, self.app.printContext)
self.app.mainloop()
```

**Comment by ShaunKulesa** [comment]
I have a feeling its because you cant animate and stop animating mid way through running a program.

**Comment by einarf** [comment]
Use markdown code blocks 😄 : https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by ShaunKulesa** [comment]
@einarf i swear that wasn't working earlier, now that i formatted it is it easier to understand my issue?

**Comment by jonwright** [comment]
How are you updating the variable after you called mainloop? Usually there needs to be a callback from the gui loop. E.g. when does it know to start and stop animation?

**Comment by ShaunKulesa** [comment]
I add a function to a button to update self.runv. I'll upload my code to a github.

**Comment by ShaunKulesa** [comment]
https://github.com/ShaunKulesa/Shaun-Engine/tree/main

**Comment by jonwright** [comment]
I sent you a pull request. You need to call tkExpose or _display to trigger the animate loop.

**Comment by ShaunKulesa** [comment]
Thank you so much, you are a great person.

**Comment by ShaunKulesa** [comment]
@jonwright i see this has tk.expose, are all of the things on here relevant?
http://pyopengl.sourceforge.net/pydoc/OpenGL.Tk.html

**Comment by jonwright** [comment]
This code was written to avoid needing to recompile togl. Hopefully this is vaguely compatible, most of the code comes from there.

**Comment by ShaunKulesa** [comment]
@jonwright what method would i use to reset an animation?

**Comment by ShaunKulesa** [comment]
nothing on here works except "keys" which returned nothing, http://pyopengl.sourceforge.net/pydoc/OpenGL.Tk.html.
