### ISSUE TITLE
Move object with key input.

### ISSUE THREAD

**Issue by ShaunKulesa** [jonwright/pyopengltk#24]
So i have this buts its not doing anything.
```class CubeSpinner( OpenGLFrame ):
    def initgl(self):
        
        GL.glLoadIdentity()
        GLU.gluPerspective(45, (self.width/self.height), 0.1, 50.0)
        GL.glTranslatef(0.0,0.0, -5)
        
    def redraw(self):
        pygame.init()
        for event in pygame.event.get():
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_LEFT:
                    glTranslatef(-1.0,0,0.0)```

**Comment by jonwright** [comment]
Do you call init every time you do a redraw? 
For Tk you would need to bind keys to a widget,e.g. https://pythonprogramming.altervista.org/tkinter-key-binding/

**Comment by ShaunKulesa** [comment]
I dont know, i know redraw is every frame and initgl is at the start. This is off your cube example.

**Comment by ShaunKulesa** [comment]
Ahh i see where you are coming from, i was using pygame inputs and i wasn't even running a pygame window.
